# Définition du nom du projet qui sera utiliser pour
# les conteneurs, network et volumes
name: projet_web_univ
services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=false" # si true, autorise le tableau de bord Traefik 
      - "--providers.docker=true" # permet l'interconnexion avec Docker
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      # - "8080:8080" # pour accéder au dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # important pour que Traefik communique avec Docker
    networks:
      - web
    labels:
      - "traefik.enable=true"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web
    expose:
      - "3306"

  wordpress1:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    volumes:
      - wordpress1_data:/var/www/html
    networks:
      - web
    labels:
      - "traefik.http.routers.wordpress1.rule=Host(`durand-eset.usmb-tri.fr`)"
      - "traefik.http.services.wordpress1.loadbalancer.server.url=http://wordpress1"

  wordpress2:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - wordpress1
    volumes:
      - wordpress2_data:/var/www/html
    networks:
      - web
    labels:
      - "traefik.http.routers.wordpress2.rule=Host(`durand-tri.usmb-tri.fr`)"
      - "traefik.http.services.wordpress2.loadbalancer.server.url=http://wordpress2"

networks:
  web:
    driver: bridge

volumes:
  db_data:
  wordpress1_data:
  wordpress2_data:
