# Définition du nom du projet qui sera utiliser pour
# les conteneurs, network et volumes
name: projet_web_univ
services:
  reverse-proxy:
    image: traefik
    command:
      - --accesslog=true # permet l'affichage des logs
      - --log.level=INFO # affiche les logs au niveau INFO (par défaut, ERROR)
      - --providers.docker=true # permet de directement se connecter au conteneur docker
      - --entrypoints.web.address=:80 # autorise l'accès avec le port 80 http
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # important pour que Traefik communique avec Docker
    networks:
      - web
    labels:
      - "traefik.enable=true"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:${SQL_ROOT_PASSWORD} # permet son accès en mode root sans savoir les utilisateurs présent dans la db
    volumes:
      - ./sql:/var/lib/mysql
      - ./sql/backup.sql:/docker-entrypoint-initdb.d/dump.sql:ro # définit le dump sql de la db pour qu'elle soit importer au lancement
    networks:
      - web
    expose:
      - 3306

  wordpress1:
    image: wordpress:5.8.3
    restart: always
    depends_on:
      - db
    volumes:
      - ./wordpress_tri:/var/www/html
    networks:
      - web
    labels:
      - "traefik.http.routers.wordpress1.rule=Host(`${WORDPRESS1_HOST}`)" # définit quelle URL sera utilisée pour matcher avec le reste des règles
      - "traefik.http.routers.wordpress1.entrypoints=web" # autorise le port 80
      - "traefik.http.services.wordpress1.loadbalancer.server.url=http://wordpress1" # renvoi sur le site herbergé sur wordpress1

  wordpress2:
    image: wordpress:5.8.3
    restart: always
    depends_on:
      - db
    volumes:
      - ./wordpress_eset:/var/www/html
    networks:
      - web
    labels:
      - "traefik.http.routers.wordpress2.rule=Host(`${WORDPRESS2_HOST}`)" # définit quelle URL sera utilisée pour matcher avec le reste des règles
      - "traefik.http.routers.wordpress2.entrypoints=web" # autorise le port 80
      - "traefik.http.services.wordpress2.loadbalancer.server.url=http://wordpress2" # renvoi sur le site herbergé sur wordpress2

networks:
  web:
    driver: bridge
